const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94775704025"
const SESSION_ID = "PRABATH-MD~4FAAzYIZ#8ucjGFsV6Fuhk8WXDlRXPKbtvXRE9uVVWOaCh_GpKgk"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
